### ISSUE TITLE
ol.layer.Group not implemented?

### ISSUE THREAD

**Issue by pmeems** [quentin-ol/ngx-openlayers#100]
I'm trying to create 3 layer groups. One with baselayers, one with theme layers and one with data layers.
These groups I want to use to create a simple layer control: 3 pulldown menus which each list their layers so I can set the visibility and opacity.

I can't find `<aol-layer-group [name]="'Baselayers'" >` or similar.
Isn't this implemented or am I missing something?

**Comment by quentin-ol** [comment]
not yet.
A PR would be welcome though!

**Comment by quentin-ol** [comment]
implemented in #120. Thanks @samuelgirard-cgi.
