### ISSUE TITLE
compatibility with openlayers 4.4.x

### ISSUE THREAD

**Issue by akkumar** [quentin-ol/ngx-openlayers#106]
Currently - package.json dependency reads as follows: 

`"openlayers": "4.0.x || 4.1.x"`    

The latest release of openlayers - according to npmjs - [https://www.npmjs.com/package/openlayers](https://www.npmjs.com/package/openlayers) is 4.4.1 . 

Wondering if there is/are any known issue(s) preventing an upgradation of the same ?

**Comment by seidlt** [comment]
I am working with version 4.4.1 for a while now and I had no issues. However, I did no extensive testing specific for the version upgrade. But I would appreciate to upgrade to 4.4.1 since issue #105 seems to be solved with the new version.

**Comment by quentin-ol** [comment]
I've pushed a new version that depends on Openlayers 4.4.x. 
Thanks everyone for the feedback!
