### ISSUE TITLE
how can i access buffer?

### ISSUE THREAD

**Issue by ognjenmarcheta** [quentin-ol/ngx-openlayers#107]
i want to buffer layers outside of view? any idea?

**Comment by quentin-ol** [comment]
If I understand well, you want to "load" a layer without displaying it, right ?
One way to achieve this is to set the opacity of the layer to 0. It's still rendered but it won't show up. Obviously, this isn't side-effects free, .e.g. features of that layers can be clicked, etc.

**Comment by ognjenmarcheta** [comment]
Actually i found solution for this. And it's described even in their official examples:
https://openlayers.org/en/latest/examples/preload.html
