### ISSUE TITLE
aol-geometry-linestring over International Date Line bug

### ISSUE THREAD

**Issue by Pitirus** [quentin-ol/ngx-openlayers#122]
Hello,

I think I found a bug when using aol-geometry-linestring. When trying to create linestring over International Date Line it isn't drawn over it.
 
Here is a plunker: [https://embed.plnkr.co/C2Y5mb/](https://embed.plnkr.co/C2Y5mb/)

 I am not sure if it's only in this library or if it originates from OpenLayers API.

**Comment by quentin-ol** [comment]
Sorry for the delay, I'm working on a deadline. I appreciate the effort you put in providing an example. Will definitely look into it.

**Comment by quentin-ol** [comment]
Btw, what do you mean by drawn over it. If I run your example in Safari, I do see the dashed red linestring.

**Comment by Pitirus** [comment]
[https://imgur.com/a/wRZB4](This is what I can see), it goes around the globe. Instead it should go the shortest way which is over the International Date Line.

**Comment by quentin-ol** [comment]
@Pitirus Ok, I get the same behavior. I was confused as to what was expected.
The drawing of the line itself is handled by openlayers. ngx-openlayers is only feeding your linestring to openlayers. You might want to report to them instead
