### ISSUE TITLE
Displaying GPX Data

### ISSUE THREAD

**Issue by MaiHei** [quentin-ol/ngx-openlayers#135]
Hey, 

i am trying to display gpx data in a layer, as in the example on the openlayers website. 

My code for the layer looks like this: 
```
<aol-layer-vector>
    <aol-source-vector [url]="'https://openlayers.org/en/v4.5.0/examples/data/gpx/fells_loop.gpx'">
    </aol-source-vector>
</aol-layer-vector>
```

This throws me the ol-errorcode 7, that says "format must be set when url is set". In the example format is set as ol.format.GPX(). 

I've searched a lot, but I haven't found any way to set this format. So is there any way to set format to GPX?

**Comment by vgossking** [comment]
you need to provide format, in this case is  ol.format.GPX()

`
import { format} from 'openlayers';
this.format = new format.GPX();
<aol-source-vector *ngIf="currentRoute.gpx"  [url]="currentRoute.gpx.path" [format]="format">
`

**Comment by MaiHei** [comment]
Thanks for your help, this fixed the problem.
