### ISSUE TITLE
Get Coordinates of drawn polygon feature.

### ISSUE THREAD

**Issue by mhosman** [quentin-ol/ngx-openlayers#174]
I'm not able to use getCoordinates() in order to get polygon drawn coordinates like this:

```
onDrawEnd(feature: Feature) {
       console.log(feature.getGeometry().getCoordinates());
}
```

getCoordinates() just doesn't exist.

**Comment by mhosman** [comment]
I can't find the way to get coordinates once a polygon I drawn.

**Comment by mhosman** [comment]
Anybody? Thanks

**Comment by davinkevin** [comment]
Sorry, I totally miss this message 😊

@gasperiguillaume could you provide an example to this question?

**Comment by mhosman** [comment]
I just don't have an example because I don't know how to get coordinates. The idea is to draw a polygon in the map and get the resulting coordinates. Also I want to pick up a color for that polygon before starting to draw. 

In OpenLayers, the way to get coordinates from a polygon is using getCoordinates():

[https://gis.stackexchange.com/questions/248373/highlight-polygon-coordinates-using-openlayers-4
](https://gis.stackexchange.com/questions/248373/highlight-polygon-coordinates-using-openlayers-4
)[https://openlayers.org/en/latest/examples/polygon-styles.html](https://openlayers.org/en/latest/examples/polygon-styles.html)

How can I get coordinates from a polygon?

**Comment by digoburigo** [comment]
Hi, i don't know if this is what you want. But i was able to find it like this. 
`Polygon.fromExtent(e.feature.getGeometry().getExtent()).getCoordinates())`
Give it i try and tell me if worked for you.

**Comment by mhosman** [comment]
Hey @digoburigo, thanks for your reply! I'm not able to import Polygon into TS file (?)

**Comment by digoburigo** [comment]
I install with npm. `npm install ol @types/ol --save` and import like this `import Polygon from 'ol/geom/polygon';`. But i was testing and this function returns a regular polygon based on the drawed polygon. So i think its not what you want, because it takes the extent of the drawed polygon and make a new one with the points of the corners and make it regular

**Comment by mhosman** [comment]
If there's any way to add that polygon to the map maybe could work for me. I'll check.

**Comment by gasperiguillaume** [comment]
@mhosman 

Is it what you are trying to do ?
[https://angular-2zczhc.stackblitz.io](url)

**Comment by mhosman** [comment]
That's great! Thank you @gasperiguillaume
