### ISSUE TITLE
NPM Audit with High vulnerabilities

### ISSUE THREAD

**Issue by mhosman** [quentin-ol/ngx-openlayers#180]
Vulnerabilities for ngx-openlayers package: 

>  High:             Downloads Resources over HTTP
> 
>  Package:          closure-util
> 
>  Patched in:       No patch available
> 
>  Dependency of:    ngx-openlayers
> 
>  Path:             ngx-openlayers > openlayers > closure-util
> 
>  More info:        https://nodesecurity.io/advisories/165
> 
-------------------------------------------------------------------------------
> 
>  High:             Regular Expression Denial of Service
> 
>  Package:          fresh
> 
>  Patched in:       >= 0.5.2
> 
>  Dependency of:    ngx-openlayers
> 
>  Path:             ngx-openlayers > openlayers > closure-util > send > fresh
> 
>  More info:        https://nodesecurity.io/advisories/526

There are another moderate vulnerabilities for this package. Please run `npm audit`.
It would be great to have a version that fix these problems.

**Comment by mhosman** [comment]
I think maybe this will be fixed once the library is updated to OpenLaters 5.0

**Comment by Neonox31** [comment]
Thanks for reporting this, we gonna check.
Just a reminder that PR are welcomed 😉

**Comment by mhosman** [comment]
Yeah I know @Neonox31 I will try to help 👍
