### ISSUE TITLE
Receiving coordinates from observables..

### ISSUE THREAD

**Issue by tbowmo** [quentin-ol/ngx-openlayers#187]
I'm trying to get the following to work:

```
<aol-map [width]="'500px'" [height]="'300px'">
  <aol-view [zoom]="4">
    <aol-coordinate [x]="invite.nerdSite.x" [y]="invite.nerdSite.y" [srid]="'EPSG:4326'"></aol-coordinate>
  </aol-view>
  <aol-layer-tile>
    <aol-source-osm></aol-source-osm>
  </aol-layer-tile>
 </aol-map>
```
invite object fetched from a webservice. It shows a point just north of Antarctica, despite the fact that the real point is on the northern hemisphere.

If I hardcode the values instead as [x]="9.111" [y]="56.22" then it works fine.. So Somehow I must be missing something.. But what?

**Comment by Dji75** [comment]
A little bit late (23 days ago !) but maybe try to add an *ngIf in `<aol-view> `: 
  ```
<aol-view [zoom]="4" *ngIf="invite && invite.nerdSite">
    <aol-coordinate [x]="invite.nerdSite.x" [y]="invite.nerdSite.y" [srid]="'EPSG:4326'"></aol-coordinate>
  </aol-view>
```

**Comment by tbowmo** [comment]
I already have an *ngIf on an outer div.. 

Just tried adding *ngIf="invite.nerdSite" to aol-view, but not helping..

I get a point off the coast of South Africa, instead of Denmark.

If I do
```
<aol-map [width]="'500px'" [height]="'300px'">
  <aol-view [zoom]="4">
    <aol-coordinate [x]="9" [y]="56.5" [srid]="'EPSG:4326'"></aol-coordinate>
  </aol-view>
  <aol-layer-tile>
    <aol-source-osm></aol-source-osm>
  </aol-layer-tile>
 </aol-map>
```

I get the correct place, but If I do the following:
```
    <aol-coordinate [x]="9" [y]="'56.5'" [srid]="'EPSG:4326'"></aol-coordinate>
```

Then I get a point in south affrica region, the only difference is the added ' ' around the [y] parameter.

**Comment by tbowmo** [comment]
Turns out it's a string / number conversion issue.. Apparently my backend returned the the coordinates as string values, instead of number, and even though I had defined the interface as using number, it was still a string.

**Comment by Dji75** [comment]
Nice to see you got the point.

> my backend returned the the coordinates as string values, instead of number, and even though I had defined the interface as using number

Interface is just describing what you expect, not what you want. If the backend answer a string, you should put a string in your interface, nothing else. You can also wrap the backend raw result from `any `to your interface after having converted the variable from string to number.

Lots of `Date` conversion works this way. Backends returns dates from strings in UTC format, you have to parse them to convert into `Date` objects.
