### ISSUE TITLE
Add short code to show how to add the module

### ISSUE THREAD

**Issue by HarelM** [quentin-ol/ngx-openlayers#189]
Most libraries have a short section to show how to add the relevant module to angular application module.
I think it would be beneficial to new developers that would like to use this library like me.
For example, see the setup section here:
https://github.com/nicky-lenaers/ngx-scroll-to

**Comment by HarelM** [comment]
Probably css file instructions are needed too...

**Comment by aymeric-duchein** [comment]
Hi! To use this library, simply add AngularOpenLayersModule to your module
```typescript
@NgModule({
  ...
  imports: [
    ...
    AngularOpenlayersModule,
    ...
  ],
  ...
})
export class AppModule { }
```
If you think something is missing, a PR to improve the documentation is always welcome!

**Comment by HarelM** [comment]
Feel free to accept it :-)
