### ISSUE TITLE
is updateWhileInteracting input is missing from LayerVectorComponent

### ISSUE THREAD

**Issue by HarelM** [quentin-ol/ngx-openlayers#198]
I might be missing something, but I think `updateWhileInteracting` is missing from `LayerVectorComponent`.
I can see it here:
https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector.html
But I can't see it in the code...
Assuming I'll send a pull request will someone be able to merge it and create a new npm package?
My last pull request is very small and is waiting for almost two weeks now... :-/
Should I create a fork instead? Can I help maintain this package? I'm migrating my site from leaflet to OL and I would very much like to use this library...

**Comment by HarelM** [comment]
I'm asking mainly because I added a custom interaction to move a feature and the move does not get "animated". I'll see if I can create a stackblitz to illustrate the issue.

**Comment by HarelM** [comment]
Any updates on this? I now see that I need this flag in order to show vector data while animating the map to rotate and pan...

**Comment by HarelM** [comment]
Sorry, meant `updateWhileAnimating`. should be the same effort i guess...

**Comment by HarelM** [comment]
I've created a pull request for this. I hope it will be merged. I've tested it on my site and it seems to be working as expected. If you could create a new next version it will be great.

**Comment by HarelM** [comment]
@maintainers Any change to get this merged? I really really don't want to create a npm package only for this...

**Comment by Neonox31** [comment]
`1.0.0-next.5` is on its way, sorry for the delay.

**Comment by HarelM** [comment]
Great!!! thanks!!! Last thing lest is the OL 5 migration. Any new about that?

**Comment by Yakoust** [comment]
@HarelM can we close this issue?


> Great!!! thanks!!! Last thing left is the OL 5 migration. Any new about that?

We are close to merge #183
