### ISSUE TITLE
Update deps. to Angular 7.0

### ISSUE THREAD

**Issue by mhosman** [quentin-ol/ngx-openlayers#206]

**Comment by mhosman** [comment]
No news about this? I still get warning...

`ngx-openlayers@1.0.0-next.2 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by Neonox31** [comment]
Fixed by commit https://github.com/quentin-ol/ngx-openlayers/commit/f4330af4a4078c55fc57c801b1a45471b3c595e6, will be in next prerelease
