### ISSUE TITLE
Support circle geometry

### ISSUE THREAD

**Issue by HarelM** [quentin-ol/ngx-openlayers#208]
Hi,

Would be great if this library had wrapped the circle geometry.
Main usage: I want to show a GPS location with a changing accuracy circle - using style seems incorrect as the accuracy is in meters and not pixels is zoom dependent...

https://openlayers.org/en/latest/apidoc/module-ol_geom_Circle-Circle.html

**Comment by kekel87** [comment]
https://github.com/quentin-ol/ngx-openlayers/pull/210

**Comment by HarelM** [comment]
Thanks @kekel87!
I hope this will be merged soon and a new version will be released...
