### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by tbowmo** [quentin-ol/ngx-openlayers#220]
It seems that there is a lot of outdated dependencies, when installing 1.0.0-next.4, I get the following warnings

```
npm WARN deprecated openlayers@4.4.2: Please use the ol package instead
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated uws@9.14.0: stop using this version
```

I have not looked into the source (yet) so I do not know if it's a painless upgrade of the mentioned libraries.

**Comment by cyberrranger** [comment]
it is even worse, the package https://www.npmjs.com/package/openlayers is deprecated, the new package is https://www.npmjs.com/package/ol

**Comment by Yakoust** [comment]
> it is even worse, the package https://www.npmjs.com/package/openlayers is deprecated, the new package is https://www.npmjs.com/package/ol

https://github.com/quentin-ol/ngx-openlayers/pull/183
