### ISSUE TITLE
Clustered Features

### ISSUE THREAD

**Issue by bagasprakarso** [quentin-ol/ngx-openlayers#61]
Hi Quentin,

Is Clustered Features like [http://openlayers.org/en/latest/examples/cluster.html](url) not include in this library?

cause when i'm implementing it using this code

`
    <aol-layer-vector>
        <aol-source-cluster>`

i've got 

> Error: Template parse errors:
'aol-source-cluster' is not a known element:

Thanks

**Comment by achimha** [comment]
Only a subset of OL4 is implemented. It's usually trivial to add things, just create a component and map all properties.

**Comment by greggguru** [comment]
If no one else is already working on adding clusters, I will do it. 

Happy with the new project name too, fits great.

**Comment by quentin-ol** [comment]
@greggguru AFAIK, no one is publicly working on this right now. Would be greatly appreciated though!

**Comment by greggguru** [comment]
Ack, best intention to get this done quickly has failed. I'm sorry. I still would like to implement this feature. Let's see what this weekend will allow me to complete.

**Comment by MSkraburski** [comment]
@greggguru are you working on it currently? Would be extremely grateful if you complete implementation of that feature. I highly need that to my Angular 4 app but unfortunately I am not capable of creating that feature on my own. Keep my fingers crossed.
Best regards,
Mikołaj

**Comment by codeMonkeysBe** [comment]
Hi yall. I want to help with implementing this. 

I had something in mind like the following

```html
<aol-layer-vector>
   <aol-source-cluster>
      <aol-feature> or other like sour
```
That ok ?

**Comment by HarelM** [comment]
Was this implemented by anyone?
I see that `<aol-source-cluster>` exists in the code, but I couldn't understand how to use it...

**Comment by davinkevin** [comment]
You can find an example here => https://quentin-ol.github.io/ngx-openlayers/examples/cluster
The source code is [here](https://github.com/quentin-ol/ngx-openlayers/blob/next/src/app/cluster/cluster.component.ts)

**Comment by HarelM** [comment]
P.S thanks for the quick response!

**Comment by HarelM** [comment]
I now see that what I'm looking for is discussed here: #186, I'll move my question there.

**Comment by HarelM** [comment]
I'm guessing this is implemented and can be closed, right? (So that future developers wouldn't think this is still not implemented since it is open).
