### ISSUE TITLE
Changing Map Co-ordinates

### ISSUE THREAD

**Issue by giridharkl** [quentin-ol/ngx-openlayers#82]
Hello
I was trying to dynamically load lon and lat from two input boxes and draw the map on a div. However with default values I could draw the map. But when I change the input box values the map does not center to the new lon lat values. Due to lack of any good example I am struggling to achieve this. Could you please show us any example. I have gone through the example in the code.

Thanks
Giridhar

**Comment by quentin-ol** [comment]
closing this. Please reopen if needed.
