### ISSUE TITLE
Problem with instalation

### ISSUE THREAD

**Issue by ctxdl** [quentin-ol/ngx-openlayers#83]
Hello  i have this problem when installing and initiation the component 

localhost/:3000 Error: Fetch error: 404 Not Found
  Instantiating http://localhost:3000/angular2-openlayers
  Loading http://localhost:3000/app/mobile-content/mobile-content.module.js
  Loading http://localhost:3000/app/app.module.js
  Loading http://localhost:3000/app/main.js
  Loading app
    at fetch.js:37
    at ZoneDelegate.invoke (zone.js:391)
    at Zone.run (zone.js:141)
    at zone.js:818
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:191)
    at drainMicroTaskQueue (zone.js:584)

**Comment by quentin-ol** [comment]
Could you describe how you end up with this error?
A 404 error is a HTTP code that your HTTP server returns the resource you're asking is not available, e.g., requiring page `http://localhost:3000/page-that-does-not-exist.html`

**Comment by quentin-ol** [comment]
Closing this. No more activity/other reports of this since 23days
