### ISSUE TITLE
NPM package name

### ISSUE THREAD

**Issue by quentin-ol** [quentin-ol/ngx-openlayers#92]
Hello everyone,

Since Angular has moved to 4.x versions and since we are already those, would it make sense to name the package angular4-openlayers?
To my understanding, this raises a few concerns:
 - same package under 2 different names
 - devs still using angular2 might think this lib is not for them
Opinions ?

**Comment by achimha** [comment]
A very welcome move.

However, I would suggest `ngx-openlayers`. The term "ngx" is commonly used for Angular 2+. The changes from Angular 2 to Angular 4 are minor and the changes from Angular 4 to Angular 5 (due out in September) will be minor as well. Wouldn't make sense to change the package name again because of Angular 5.

**Comment by quentin-ol** [comment]
@achimha Thanks for your feedback.
I'm also in favour of moving to `ngx-openlayers`. Obviously, this would require a few changes, let's try to sum that up in here and see how that would affect people using it:

- rename the git repository
- rename the package in `package.json`
- publish a new npm package
- rename/change the gitter channel.
- change all occurrences of angular2-openlayers in the documentation.

Anything missing ?
Also, to those using it in production, how would it impact you if those changes were applied ? 
\cc @Neonox31, @davinkevin , @Yakoust

**Comment by achimha** [comment]
I've had 4 other packages that I use in my enterprise application change from angular2-x to something else.  The old packages still remain in npm so people can choose to upgrade when they like.

In the Angular ecosystem it is accepted to break things from time to time -- Angular itself comes with incompatible changes every couple of months.

**Comment by quentin-ol** [comment]
@achimha I agree. 

Leaving this open until the end of the week so that others may chime in. 
If we reach a consensus towards renaming then we'll do it.

**Comment by davinkevin** [comment]
It's OK for us, we already think about the naming problem due to the version of angular, and `ngx-openlayers` and `angular-openlayers` was proposed internally.

Right now, this doesn't have any impact in our code, our main task is to implement what we need in the library.

**Comment by quentin-ol** [comment]
alright, let's proceed then.

**Comment by quentin-ol** [comment]
renaming is on-going. Things might break in the meantime.

**Comment by quentin-ol** [comment]
Renaming is done, the npm package is live and the travis build passes. 
Still need to deprecate the previous package in npm and we can close this issue.

**Comment by davinkevin** [comment]
Welcome to ngx-openlayers 🎉

**Comment by Neonox31** [comment]
Great ! 🎆
