### ISSUE TITLE
Handle Click on features

### ISSUE THREAD

**Issue by vetemi** [quentin-ol/ngx-openlayers#93]
I have a question; though I'm not sure if I'm right here but I hope you can help me anyways. 

I'm very new to both Angular and Openlayers. My goal is to detect the event when an user clicks on one of a bunch of generated features (with markers on map) in order to display the details of the clicked feature. My app is basically like the example of this project and I'd like to have something like this:
`
...
<aol-feature *ngFor="let item of items" (click)="onSelect(item)"></aol-feature>
....
`

But this does not work unfortunately. What is the right way of doing this? I've seen that the map has an exposed method 'onClick' but how would I use it to get the clicked features?

Thanks and best regards

**Comment by quentin-ol** [comment]
Issue #84 answer is exactly what you're looking for. Could you provide a PR that adds this piece of info in the documentation? We'd be very grateful!

**Comment by vetemi** [comment]
We are creating an open source map application which uses most of the features provided by this awesome library. Once we're done, I'll definitely add some insights to documentation or example.
