### ISSUE TITLE
Caching WMS Tiles  

### ISSUE THREAD

**Issue by xtarx** [quentin-ol/ngx-openlayers#97]
Is there anyway provided  to cache the tiles instead of being re-loaded on every page visit?

**Comment by quentin-ol** [comment]
If there is a way, it's within OpenLayers itself. ngx-openlayers is just a collection of thin wraps (components) around OpenLayers objects. You might want to take a look at their documentation and see if there is anything that might you.

In short, no, ngx-openlayers does not cache WMS tiles.
