### ISSUE TITLE
Get all features.

### ISSUE THREAD

**Issue by jeremieca** [quentin-ol/ngx-openlayers#98]
Hello,

After map loaded, I would like to iterate over all features to make some change. For instance, change opacity (style) of some Feature polygons after a few seconds.

Where can I find a list of all Features ?

Thanks !

**Comment by quentin-ol** [comment]
How do you create your features. The intended use is to add the feature using the aol-feature component like this:
```html
[...]
<aol-source-vector>
    <aol-feature *ngFor="let m of markers">
        <aol-geometry-point>
          <aol-coordinate [x]="m.x" [y]="m.y" [srid]="'EPSG:4326'"></aol-coordinate>
        </aol-geometry-point>
        <aol-style>
          <aol-style-circle [radius]="m.radius">
            <aol-style-stroke [color]="'black'" [width]="m.width"></aol-style-stroke>
            <aol-style-fill [color]="'green'"></aol-style-fill>
          </aol-style-circle>
        </aol-style>
      </aol-feature>
</aol-source-vector>
[...]
```
If used in this way, features are mapped to the markers list. If you need to change a feature coordinate, change the datum that the feature is mapped to, i.e. `markers[0].x = myNewXCoordinate`. The same principle can be applied to styles, though, you have to know that an issue in Openlayers prevents updating the styles for now...

**Comment by jeremieca** [comment]
Ok perfect. Thanks. I misunderstood the doc. :)

**Comment by maher1991** [comment]
Hello, I need a basic example for displaying a polygon:
I tried something like the code below but it doesn't give me a result:

 ```
                <aol-feature>
                  <aol-geometry-polygon>
                    <aol-collection-coordinates [coordinates]="[[10.1030,36.6252],[10.1242,36.4856],[10.4737,36.3807]]"  [srid]="'EPSG:4326'">
                    </aol-collection-coordinates>
                  </aol-geometry-polygon>
                  <aol-style-fill [color]="'red'"></aol-style-fill>
                </aol-feature>

**Comment by davinkevin** [comment]
We are thinking about documentation with @aymeric-duchein and we will try to provide a storybook of the component to show different use-case requested by users...
