### ISSUE TITLE
Setting minResolution and maxResolution prevents showing layer

### ISSUE THREAD

**Issue by pmeems** [quentin-ol/ngx-openlayers#99]
When I have this `<aol-layer-tile [visible]="true">` around my `<aol-source-tilewmts ... >` the layer is shown.
But when I add minResolution and maxResolution:  `<aol-layer-tile [visible]="true" [minResolution]=2000 [maxResolution]=20000>`  the layer is not shown at all, although the resolutions seem OK.

Am I not writing it correctly or are these properties not implemented.

**Comment by quentin-ol** [comment]
Careful with cases in AngularX, input properties are written using the camelCase in `ts/js` code; i.e. in the component declaration; and using kebab-case in the view `html`.

the correct inputs would be `[min-resolution]` and `[max-resolution]`.
